### ISSUE TITLE
add nunit 3.x support

### ISSUE THREAD

**Issue by kcamp** [chris-peterson/Kekiri#13]
Our testing projects vary between nunit 2.6.4 and nunit 3.5

It would be useful to be able to support the nunit 3.5 projects with Kekiri in a low-friction way.

Are there any thoughts or ideas to support this?  The strong name of nunit.framework has changed between 2 and 3, so an assembly redirect is out.  Simply subclassing `Kekiri.Test` and applying the `OneTimeSetUp` and `OneTimeTearDown` attributes [local to my own project] is an "almost" solution, but falls short in that the `Kekiri.ThenAttribute` can't be used because of the dependency on nunit 2.6.
Creating a new `ThenAttribute` class isn't an option because of the `internal interface IStepAttribute` [no access to the type to implement it.]

Any ideas?  A straight update to nunit 3.5 in the Kekiri solution leaves a solid portion of tests in a failing state, so any update would require additional work, for certain.

**Comment by kcamp** [comment]
Upon reviewing the test runs, it looks like maybe some of the tests appear to fail with NUnit 2.6.4, too?
`Kekiri.TestSupport.Scenarios.Exceptions.When_fixture_has_a_parameterized_given_scenario`
appears to fail in the R# runner with the following:
```
SetUp : Kekiri.Exceptions.ScenarioStepMethodsShouldNotHaveParameters : Error in 'When_fixture_has_a_parameterized_given_scenario':
The method 'Given' is in a ScenarioTest and cannot have parameters
   at Kekiri.Impl.ScenarioMapper.GetStepFromMethod(MethodInfo method, IEnumerable`1 parameters) in C:\git\Kekiri\src\Library\Impl\ScenarioMapper.cs:line 41
```

Most of the tests in that namespace fail; is that intended?  If it is, then the behavior with nunit3 is similar, and you can disregard that portion of the previous comment.

**Comment by smarts** [comment]
Some more info re: this issue - [NUnit's source code specifically states that `TestAttribute` is not to be inherited from](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestAttribute.cs#L37).

**Comment by chris-peterson** [comment]
Will try to address this in https://github.com/chris-peterson/Kekiri/tree/v4/.  

In V4, the NUnit coupling is externalized, so we could potentially create additional satellite builds for `Kekiri.TestRunners.NUnit`.

**Comment by chris-peterson** [comment]
v4 now uses NUnit 3.6.1
