### ISSUE TITLE
xUnit: Paramatereized Scenarios are not supported

### ISSUE THREAD

**Issue by chris-peterson** [chris-peterson/Kekiri#19]
When trying to add `[Example]` to `[Scenario]`, xUnit complains --

```Error Message:
 System.InvalidOperationException : [Fact] methods are not allowed to have parameters. Did you mean to use [Theory]?```

**Comment by andyalm** [comment]
If you want to use an Example, you have to use ScenarioOutline instead.

**Comment by chris-peterson** [comment]
:doh:

**Comment by andyalm** [comment]
It would be interesting to see if it's possible to give a more helpful error message
