### ISSUE TITLE
Kekiri.IoC.Container is missing Resolve(Type type) method

### ISSUE THREAD

**Issue by ebelew** [chris-peterson/Kekiri#9]
When using Automapper with IoC, it accepts a method `Func<Type, object> constructor` to specify how to construct resolvers, mappers, etc. 

However, Kekiri only has `T Resolve<T>()`, and no `object Resolve(Type type)`

**Comment by chris-peterson** [comment]
This can be supported by defining an extension method in your source:

```c#
    public static class ContainerExtensions
    {
        public static object Resolve(this Container container, Type type)
        {
            var resolveMethod = typeof(Container).GetMethod("Resolve").MakeGenericMethod(type);
            return resolveMethod.Invoke(container, null);
        }
    }
```

**Comment by ebelew** [comment]
Yes, that's the workaround I chose also, but it would be awesome if the method was available by default.

**Comment by chris-peterson** [comment]
I really want to emphasize usage of the generic method, so I'm going to close this.
